/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventoryProcessRouteImport } from './routes/inventoryProcess'
import { Route as IndexRouteImport } from './routes/index'

const InventoryProcessRoute = InventoryProcessRouteImport.update({
  id: '/inventoryProcess',
  path: '/inventoryProcess',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventoryProcess': typeof InventoryProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventoryProcess': typeof InventoryProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventoryProcess': typeof InventoryProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inventoryProcess'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventoryProcess'
  id: '__root__' | '/' | '/inventoryProcess'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryProcessRoute: typeof InventoryProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventoryProcess': {
      id: '/inventoryProcess'
      path: '/inventoryProcess'
      fullPath: '/inventoryProcess'
      preLoaderRoute: typeof InventoryProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryProcessRoute: InventoryProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
